# ----- OPERATIONS

type Query {

    """ Retrieve a text document by its ID. """
    textDocument(id: ID!): TextDocument

    """ Retrieve a text analysis by its ID. """
    textAnalysis(id: ID!): TextAnalysis

}

type Mutation {

    """ Create a new text analysis based on an existing text document. """
    createTextAnalyis(textDocumentId: ID!): CreateTextAnalyisResponse!

    """ Add a highlight to a text analysis. """
    addHighlight(textAnalysisId: ID!, paragraphId: ID!, start: Int!, end: Int!): Highlight

    """ Remove an existing highlight from a text analysis. """
    removeHighlight(textAnalysisId: ID!, paragraphId: ID!, highlightId: ID!): RemoveHighlightResponse!

}

# ----- MAIN TYPES

""" A text document containing paragraphs. """
type TextDocument {
    id: ID!
    title: String!
    author: String
    paragraphs: [Paragraph!]!
}

""" A single paragraph of a text document. """
type Paragraph {
    id: ID!
    text: String!
}

""" An analysis of an existing text document. """
type TextAnalysis {
    id: ID!
    title: String!
    author: String
    paragraphs: [ParagraphAnalysis!]!
}

""" A paragraph with the analysis of its text. """
type ParagraphAnalysis {
    id: ID!
    text: String!
    highlights: [Highlight!]!
}

""" A highlighted range within a paragraph. """
type Highlight {
    id: ID!
    start: Int!
    end: Int!
}

# ----- RESPONSE TYPES

""" Response returned after removing a highlight. """
type RemoveHighlightResponse {
    success: Boolean!
}

type CreateTextAnalyisResponse {
    id: String
}