# ----- OPERATIONS

type Query {

    """ Get a text document by its ID """
    textDocument(id: ID!): TextDocument

}

type Mutation {

    """ Add a highlight to a text document """
    addHighlight(textDocumentId: ID!, paragraphId: ID!, start: Int!, end: Int!): Highlight

    """ Remove an existing highlight from a text document """
    removeHighlight(textDocumentId: ID!, paragraphId: ID!, highlightId: ID!): RemoveHighlightResponse!

}

# ----- MAIN TYPES

""" A text document with paragraphs and highlights """
type TextDocument {
    id: ID!
    title: String!
    author: String
    paragraphs: [Paragraph!]!
}

""" A single paragraph of a text document """
type Paragraph {
    id: ID!
    text: String!
    highlights: [Highlight!]!
}

""" A highlighted text range within a paragraph """
type Highlight {
    id: ID!
    start: Int!
    end: Int!
}

# ----- RESPONSE TYPES

""" Response for removing a highlight """
type RemoveHighlightResponse {
    success: Boolean!
}