# ----- OPERATIONS

type Query {
    TextDocument(id: ID!): TextDocument
}

type Mutation {
    addHighlight(textDocumentId: ID!, paragraphId: ID!, start: Int!, end: Int!): AddHighlightResponse
    removeHighlight(textDocumentId: ID!, highlightId: ID!): RemoveHighlightResponse
}

# ----- MAIN TYPES

type TextDocument {
    id: ID!
    title: String!
    paragraphs: [Paragraph!]!
    highlights: [Highlight!]!
}

type Paragraph {
    id: ID!
    text: String!
}

type Highlight {
    id: ID!
    paragraphId: ID!
    start: Int!
    end: Int!
}

# ----- RESPONSE TYPES

type AddHighlightResponse {
    success: Boolean!
    message: String
    highlight: Highlight
}

type RemoveHighlightResponse {
    success: Boolean!
    message: String
}