name: Deploy Text-Review to Production (Build on Server)

on:
  push:
    branches:
      - main

jobs:
  deploy-text-review-to-prod:

    name: Deploy Text-Review to Production Server via SSH
    runs-on: ubuntu-latest

    steps:

      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Read App Version Number
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: 3. Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 4. Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.package-version.outputs.current-version }}  # Tag with App Version
            ${{ env.IMAGE_NAME }}:latest                                                # Tag with Latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline