name: Deploy Text-Review to GitHub Container Registry (GHCR)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Change to Lowercase Repository Name
        id: prep
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=ghcr.io/$REPO" >> $GITHUB_ENV

      - name: 3. Read App Version Number
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: 4. Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 5. Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.package-version.outputs.current-version }}
            ${{ env.IMAGE_NAME }}:latest
          build-args: |
            NEXT_PUBLIC_GRAPHQL_ENDPOINT=http://localhost:3000/api/graphql
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline