name: Deploy Text-Review to GitHub Container Registry (GHCR)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:

  build:
    runs-on: ubuntu-latest-arm64
    steps:
      - name: 1. Check out code
        uses: actions/checkout@v4
      
      - name: 2. Convert repository name to lowercase
        id: prep
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=ghcr.io/$REPO" >> $GITHUB_ENV

      - name: 3. Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 4. Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 5. Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy_staging:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout Infrastructure Repository
        uses: actions/checkout@v4
        with:
          repository: pjurke/infrastructure
          path: 'infrastructure'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Deploy to Staging
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: infrastructure/deploy-app.yml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          options: |
            --inventory infrastructure/inventory.ini
            --extra-vars "app_name=textreview env=staging image_tag=${{ github.sha }}"

  deploy_production:
    needs: build
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://textreview.org
    steps:
      - name: Checkout Infrastructure Repository
        uses: actions/checkout@v4
        with:
          repository: pjurke/infrastructure
          path: 'infrastructure'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Deploy to Production
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: infrastructure/deploy-app.yml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          options: |
            --inventory infrastructure/inventory.ini
            --extra-vars "app_name=textreview env=production image_tag=${{ github.sha }}"