name: Deploy Text-Review to GitHub Container Registry (GHCR)

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Read App Version Number
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: 3. Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 4. Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.package-version.outputs.current-version }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline